### ISSUE TITLE
Project requirements 

### ISSUE THREAD

**Issue by danpresil** [lihaoliu-cambridge/mtmr-net#1]
Can you specify the package requirements for this project? 

Many thanks!

**Comment by CaptainWilliam** [comment]
Hi Dan:

Please refer to the main paper for requirement details.

Best Regards,
Lihao.

**Comment by CaptainWilliam** [comment]
> Can you specify the package requirements for this project?
> 
> Many thanks!



> Can you specify the package requirements for this project?
> 
> Many thanks!

Hi Dan:

Please refer to the main paper for requirement details.

Best Regards,
Lihao.

**Comment by CaptainWilliam** [comment]
> Can you specify the package requirements for this project?
> 
> Many thanks!

Hi Dan:

Please refer to the main paper for requirement details.

Best Regards,
Lihao.

**Comment by lihaoliu-cambridge** [comment]
> Can you specify the package requirements for this project?
> 
> Many thanks!

Hi Dan:

Please refer to the main page for requirement details.

Best Regards,
Lihao.

**Comment by danpresil** [comment]
Hey,
Thank you for the quick reply,

I'm still getting the same error with the following packages installed:
numpy                              1.16.3
SimpleITK                          1.2.0
tensorboardX                       1.6
torch                              0.4.1
torchvision                        0.2.2.post3

**/MTMR-NET/logs/error_logs/logs:**
`Wed, 24 Apr, 2019, 08:14:55 main.py[line:57] [INFO] Begin program`
`Wed, 24 Apr, 2019, 08:15:17 main.py[line:62] [ERROR] Traceback (most recent call last):`
`  File "/venv_python2/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])`
`  File "/MTMR-NET/preprocessing/data_handler_2d_regression.py", line 524, in __getitem__
    img_array = self.transforms(pil_image)`
`  File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)`
`  File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)`
`  File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 206, in normalize
    mean = torch.tensor(mean, dtype=torch.float32)`
`AttributeError: 'module' object has no attribute 'float32'`

`Wed, 24 Apr, 2019, 08:20:38 main.py[line:57] [INFO] Begin program`
`Wed, 24 Apr, 2019, 08:21:00 main.py[line:62] [ERROR] input and target shapes do not match: input [64 x 1], target [64] at /pytorch/aten/src/THCUNN/generic/MSECriterion.cu:12`


Dan.

**Comment by lihaoliu-cambridge** [comment]
> Hey,
> Thank you for the quick reply,
> 
> I'm still getting the same error with the following packages installed:
> numpy 1.16.3
> SimpleITK 1.2.0
> tensorboardX 1.6
> torch 0.4.1
> torchvision 0.2.2.post3
> 
> **/MTMR-NET/logs/error_logs/logs:**
> `Wed, 24 Apr, 2019, 08:14:55 main.py[line:57] [INFO] Begin program`
> `Wed, 24 Apr, 2019, 08:15:17 main.py[line:62] [ERROR] Traceback (most recent call last):`
> ` File "/venv_python2/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop samples = collate_fn([dataset[i] for i in batch_indices])`
> ` File "/MTMR-NET/preprocessing/data_handler_2d_regression.py", line 524, in __getitem__ img_array = self.transforms(pil_image)`
> ` File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__ img = t(img)`
> ` File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 163, in __call__ return F.normalize(tensor, self.mean, self.std, self.inplace)`
> ` File "/venv_python2/local/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 206, in normalize mean = torch.tensor(mean, dtype=torch.float32)`
> `AttributeError: 'module' object has no attribute 'float32'`
> 
> `Wed, 24 Apr, 2019, 08:20:38 main.py[line:57] [INFO] Begin program`
> `Wed, 24 Apr, 2019, 08:21:00 main.py[line:62] [ERROR] input and target shapes do not match: input [64 x 1], target [64] at /pytorch/aten/src/THCUNN/generic/MSECriterion.cu:12`
> 
> Dan.

I think you should use Pytorch 0.3.0.

I have updated the version I used.

Best Regards,
Lihao.
