### ISSUE TITLE
About Data Preprocessing

### ISSUE THREAD

**Issue by lmz123321** [lihaoliu-cambridge/mtmr-net#3]
Hi, Lihao, Thanks for your great work!
I am wondering: 
Do I need to use the code in https://github.com/jcausey-astate/NoduleX_code to preprocess my original LIDC dataset firstly before doing any model training ?
Or I just have to put the original LIDC dataset under './data' and your code can preprocess them automatically ?

**Comment by lihaoliu-cambridge** [comment]
> Hi, Lihao, Thanks for your great work!
> I am wondering:
> Do I need to use the code in https://github.com/jcausey-astate/NoduleX_code to preprocess my original LIDC dataset firstly before doing any model training ?
> Or I just have to put the original LIDC dataset under './data' and your code can preprocess them automatically ?

Thanks for your question and your interest in our work.

Yes, you need to preprocess the image first. You can use the code from NoduleX project or write your own script.
