### ISSUE TITLE
constructorError in yaml file

### ISSUE THREAD

**Issue by Sakshiwala** [lihaoliu-cambridge/mtmr-net#4]
I am getting this error while ruuning the code

  raise ConstructorError(None, None, yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "./conf/log.yaml", line 32, column 18

Kindly please help me understand and solve the error

**Comment by lihaoliu-cambridge** [comment]
> I am getting this error while ruuning the code
> 
> raise ConstructorError(None, None, yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
> in "./conf/log.yaml", line 32, column 18
> 
> Kindly please help me understand and solve the error

Hi, thanks for your question. But the provided information is not enough to locate the bug. Could you please provide more details?

**Comment by Sakshiwala** [comment]
Sorry for the delay and thanks for the response.

Sir I am facing below problem, while running python main.py command
![Screenshot (19)](https://user-images.githubusercontent.com/56967634/106415650-a230f200-6475-11eb-89be-30bacf837ba6.png)

Please help

**Comment by lihaoliu-cambridge** [comment]
> Sorry for the delay and thanks for the response.
> 
> Sir I am facing below problem, while running python main.py command
> ![Screenshot (19)](https://user-images.githubusercontent.com/56967634/106415650-a230f200-6475-11eb-89be-30bacf837ba6.png)
> 
> Please help

Hi, the error happens in "yaml.safe_load()" function. I believe it is because your yaml version is too high. I suggest you degrade it to yaml 3.13.

**Comment by Sakshiwala** [comment]
> > Sorry for the delay and thanks for the response.
> > Sir I am facing below problem, while running python main.py command
> > ![Screenshot (19)](https://user-images.githubusercontent.com/56967634/106415650-a230f200-6475-11eb-89be-30bacf837ba6.png)
> > Please help
> 
> Hi, the error happens in "yaml.safe_load()" function. I believe it is because your yaml version is too high. I suggest you degrade it to yaml 3.13.

Sir I degraded the yaml version to 3.13 but it did not solve the problem. What can I do next?

**Comment by lihaoliu-cambridge** [comment]
> What

Hi, the bug is located, which is the YAML's deserialize function. So I believe it is an easy problem to solve. 

I recommend you first check your config file. Make sure there isn't any 'garbled character', 'tab', or 'blank space' included.

Second, you can run a small tutorial test case (attached below) for YAML to see if the safe_load function is working so you can better locate the error.

------------ test code ------------ 
import yaml
import io

data = {
    'a list': [
        1, 
        42, 
        3.141, 
        1337, 
        'help', 
        u'€'
    ],
    'a string': 'bla',
    'another dict': {
        'foo': 'bar',
        'key': 'value',
        'the answer': 42
    }
}

with io.open('data.yaml', 'w', encoding='utf8') as outfile:
    yaml.dump(data, outfile, default_flow_style=False, allow_unicode=True)

with open("data.yaml", 'r') as stream:
    data_loaded = yaml.safe_load(stream)

print(data == data_loaded)

**Comment by Sakshiwala** [comment]
Thank you for giving your time sir. I will try this solution.
Thank you again.
